Added linter configuration
Ugboaja-Uchechi/Hello-World pull request #1
Opened 2021-08-16 09:22 UTC by Ugboaja-Uchechi

2021-08-16 09:24 UTC, Ugboaja-Uchechi commented
Added linter styling to help debug, make the code neater and easy to understand

2021-08-16 09:43 UTC, dasileker requested changes
### **Hi @Ugboaja-Uchechi,** 

### **To Highlight**
- The linters are passing.
- The Commit are good.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-16 09:55 UTC, Ugboaja-Uchechi commented
Added test.md file as required by my code reviewer.

2021-08-16 10:02 UTC, AshakaE requested changes
### Hi @Ugboaja-Uchechi  🙋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 # Required Changes ♻️ 🚧 
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-16 10:02 UTC, AshakaE commented on test.md
> +node_modules/
As requested by the previous reviewer
- [ ] Please make sure this file is properly ignored by the `git` before making a `git push`

2021-08-16 10:29 UTC, Ugboaja-Uchechi commented on test.md
> +node_modules/
If I have a .gitignore file consisting of the same information as the test.md file, do I still need the test.md file.

2021-08-16 11:30 UTC, Ugboaja-Uchechi commented on test.md
> +node_modules/
I am not sure about the changes I'm to make.
1.  Is the test.md meant to be in the .gitignore file together with node_modules/
                              OR
2.  Is the test.md file meant to be a seperate file on its own

2021-08-16 13:01 UTC, mke2111 approved these changes
### Hi @Ugboaja-Uchechi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉** 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-16 13:03 UTC, merged

2021-08-20 11:24 UTC, SpaYco reviewed
Hello 👋,

_This is an additional review as a result of the second opinion request._

As this feature is still new, there are cases where a request wouldn't be noticed, sadly, yours was one of them, I just noticed this request now, and wanted to apologize for the delay

Thankfully I see that the problem got resolved and you continued with your projects!

Good luck with future projects and keep rocking 🚀!